### ISSUE TITLE
Bad PDU length 0

### ISSUE THREAD

**Issue by monsieurtoc** [bombadil/mod_proxy_msrpc#1]
Hi,

I've set up a apache reverse proxy with apache 2.4.4-2 and built your module. I've also added "OutlookAnywherePassthrough On" in my rproxy.conf.
The owa reverse proxy works like a charm but when launching Outlook 2010 and try to log on i get this in error log :

[proxy_msrpc:error] [pid 11895:tid 2956430192] [client 1.2.3.4.5:50352] RPC_IN_DATA: failed to read request body - bad PDU length 0
but also this at the same time
"RPC_IN_DATA /rpc/rpcproxy.dll?exchange.domain.com:6001 HTTP/1.1" 400 1693 "-" "MSRPC"

Is there any tricks to make things work ?
Thanks.

**Comment by bombadil** [comment]
Please add the configuration directive

LogLevel proxy_msrpc:trace2

reload httpd, then reproduce the issue, and provide the resulting log file.

Regards,
Micha

**Comment by monsieurtoc** [comment]
Hi,

I added the log directive as you asked. In the log files I also noticed 
that after the failure of RPC requests, Outlook tries to contact 
/autodiscover with a POST method which mod_proxy_msrpc declines. Is it 
the normal behaviour of proxy_msrpc ?

Regards,
Guillaume

**Comment by bombadil** [comment]
Hi,

Yes, the module only handles RPC_IN_DATA and RPC_OUT_DATA method requests. Can you see whether the connection used for the auto discover POST request is later being reused for the RPC request that fails? If so, this might be an issue with NTLM authentication...

Regards
Micha

monsieurtoc notifications@github.com schrieb:

> Hi,
> 
> I added the log directive as you asked. In the log files I also noticed
> 
> that after the failure of RPC requests, Outlook tries to contact 
> /autodiscover with a POST method which mod_proxy_msrpc declines. Is it 
> the normal behaviour of proxy_msrpc ?
> 
> Regards,
> Guillaume
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bombadil/mod_proxy_msrpc/issues/1#issuecomment-18485596

## 

Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by monsieurtoc** [comment]
Hi,

Thanks for the tip, I'll take a look at the NTLM authentication.

Regards,
Guillaume.

**Comment by bombadil** [comment]
Guillaume,

just some more details about the NTLM authentication issue: This is an issue that exists more or less independent from my MSRPC support module. The problem is, that Apache httpd configured as a reverse proxy cannot handle NTLM authentication correctly (see e.g. here https://issues.apache.org/bugzilla/show_bug.cgi?id=39673 ).

If the NTLM issue is the root cause for your error message, your only option for getting rid of this error message is, to avoid NTLM authentication entirely, e.g. by disabling it in the Exchange/IIS/Outlook configuration. So, if you could do that, you can at least confirm that the error message is really caused by the NTLM issue.

Regards,
Micha

**Comment by vota** [comment]
Hi Micha,

any new ideas regarding this issue? - i changed OutlookAnywhere auth to basicauth as well as IIS.. but problem persists.

Thanks,
BR

**Comment by bombadil** [comment]
Please set "LogLevel proxy_msrpc:trace2" and provide the full log.

**Comment by bombadil** [comment]
I just got some logs of the error with trace2 enabled. From reading the log, following log message order seems to indicate an issue:

```
[Wed Jun 12 10:15:02.907445 2013] [proxy_msrpc:trace2] [pid 31564] mod_proxy_msrpc.c(722): [client 10.10.10.10:49766] RPC_IN_DATA: got 1 bytes of request body from client
[Wed Jun 12 10:15:02.907471 2013] [proxy_msrpc:error] [pid 31564] [client 10.10.10.10:49766] RPC_IN_DATA: failed to read request body - bad PDU length 0
```

If only one byte has been read from the request body (which is a legit case), the PDU length cannot get determined properly yet. At least 10 bytes of request body are required to properly determine the PDU length.

**Comment by bombadil** [comment]
The code assumes that ap_get_brigade() returns at least 10 bytes when reading the request body. This cannot be taken for granted in all situations. I tried to fix that in commit e901ecf by calling ap_get_brigade() as often as needed to get at least 10 bytes of request body in the buffer before proceeding to parse the PDU length.

Please provide feedback whether that fixes the issue.

**Comment by bombadil** [comment]
If you are an affected Astaro or Sophos customer, please contact your support and request a fixed RPM for **Mantis ID 26595**.

If you got the fix, please provide feedback whether that really fixes the issue.

**Comment by bombadil** [comment]
I got positive feedback, so I consider this issue fixed.
