### ISSUE TITLE
Support for Remote Desktop Gateway servers

### ISSUE THREAD

**Issue by cyolito** [bombadil/mod_proxy_msrpc#10]
Would it be possible to also make this work to reverse proxify a Remote Desktop Gatway server (via /rpc) through apache?

**Comment by bombadil** [comment]
I have not enough information to assess how easy adding support for Remote Desktop Gateway is. So this would need some more investigations and possibly a lot of triaging to make this possible.

If you are a Sophos UTM customer, please note that the missing support for Remote Desktop Gateway was already reported in the beta for UTM 9.1 (see also here: http://www.astaro.org/showthread.php?t=47321). So it might be a good idea to ask your vendor to open a Sophos support request asking for a fix for Mantis #25441. This will at least increase attention for this issue.

**Comment by AlexH-HankIT** [comment]
Any news here?

**Comment by bombadil** [comment]
I've heard of some users that do already successfully use this module to access remote desktop gateway servers. But I have no such setup to confirm that this really works.

**Comment by AlexH-HankIT** [comment]
Thanks, i will look into it.

**Comment by ruliane** [comment]
Hi,
Did someone find a way to use mod_proxy_msrpc in front of a RD Gateway ?

**Comment by nroach44** [comment]
@bombadil I'd be happy to assist with this if you need - when trying to forward a 2016 RD GW the following is shown in the debug logs:

[proxy_msrpc:debug] [pid 8438] mod_proxy_msrpc.c(1276): [client snip] declining due to bad method: RDG_OUT_DATA
[proxy_msrpc:debug] [pid 8440] mod_proxy_msrpc.c(1276): [client snip] declining due to bad method: RDG_IN_DATA

This worked for an SBS 2011 RDGW but doesn't work for 2016, so is it possibly a case of defining a new type?

**Comment by bombadil** [comment]
Whitelisting the RDG_IN_DATA and RDG_OUT_DATA methods is just the start. The real work is then to make sure the protocol that is spoken using these methods is properly supported.

Without having read any of the involved specs I would be curious whether mapping the RDG_* methods to their existing RPC_* counter parts would be sufficient to make it work. That's something for the more courageous users to try...

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
