### ISSUE TITLE
Update Documentation for Apache Requirements - Example Conf

### ISSUE THREAD

**Issue by spacecwoboy** [bombadil/mod_proxy_msrpc#16]
First, thanks for the providing the community with a solution we've all been longing for.  There is nothing else like it.

I've been testing the module for about 3 months now - finding a couple of issues here and there to resolve, mostly with the apache config, not the mod_proxy_msrpc module.

I'm not an Apache pro, but can stumble through what's required by troubleshooting, researching documentation and digging into verbose log files.

There would be TONS of value to the community by giving vanilla/minimal example Apache conf's required to stand up the OutlookAnywhere proxy.

For instance, one hurdle I had to overcome was the tweaking of ''RequestReadTimeout'.  I was obtaining client (outlook) errors with the inability to connect to the server.  Come to find out, it was an Apache conf ('RequestReadTimeout') setting that needed to be increased.  Make sense, because the RPC over HTTPS stream.

I've combed the internet finding individual examples of the conf's, but they are in no way an 'official' source.  While many of these settings might be common-sense to the Apache guru, a noob like myself can more easily pinpoint if it's a client/server Apache/Exchange/Outlook issue - by knowing my Apache conf's are solid (or are _supposed_ to work).

Thanks again for making this available.  I know this isn't a module for amateurs to install, but a little extra documentation will surely push this product into greater use.

![requestreadtimeout](https://f.cloud.github.com/assets/5881412/2526968/6ccbcc16-b4ff-11e3-94d7-2481c31ec161.png)

**Comment by bombadil** [comment]
Hi spacecwoboy,

thanks for the reminder to publish some example configuration in the docs. I will do that soon.

Just a side note: Tweaking RequestReadTimeout should not be required as the current mod_proxy_msrpc removes mod_reqtimeout from the input filter chain as soon as it takes over the request.

Regards,
Micha Lenk

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
