### ISSUE TITLE
Doesn't build on big-endian architectures

### ISSUE THREAD

**Issue by juricast** [bombadil/mod_proxy_msrpc#18]
Hello,

Package does not build on all big endian architectures.

Build logs:

mips:
https://buildd.debian.org/status/fetch.php?pkg=mod-proxy-msrpc&arch=mips&ver=0.4-1&stamp=1391537191

powerpc:
https://buildd.debian.org/status/fetch.php?pkg=mod-proxy-msrpc&arch=powerpc&ver=0.4-1&stamp=1391530660

s390x:
https://buildd.debian.org/status/fetch.php?pkg=mod-proxy-msrpc&arch=s390x&ver=0.4-1&stamp=1391530614

sparc:
https://buildd.debian.org/status/fetch.php?pkg=mod-proxy-msrpc&arch=sparc&ver=0.4-1&stamp=1391534695

Looks like that there is no big endian support.
Is there a chance that support for big endian systems will be available in future releases?

Regards,
Jurica

**Comment by bombadil** [comment]
Hi Jurica,

Thanks for reporting the issue.

Yes, support for big endian systems will get added in a future release.

Regards,
Micha

**Comment by bombadil** [comment]
I've just pushed the following commits to address this issue:
b29e6be126f79cc6b5802ffc88a37b49881cbd94
4e3559037ee9774a5e16fc17900d58031b5cd56c
acb7b42fc2c5ac3df4d2dbcb34474457fa2f2a92
06086e192dcf114b8d79aa7ae461ed6c5e9d0c57
