### ISSUE TITLE
APR path help

### ISSUE THREAD

**Issue by jrprice78** [bombadil/mod_proxy_msrpc#19]
I have a src installed version of APR 1.4.8 and Apache 2.4.9 on Ubuntu LTS.  I am hitting a really stupid error, but I was hoping you could help me.  The configure step is failing on the APR check, likely because pkg-config cannot find APR, so its failing.

I am trying to pass APR_LIBS and APR_CFLAGS but in all honesty I am not sure what to put there and theres not a terrible amount of documentation out there.

Thanks in advance!

**Comment by bombadil** [comment]
With Ubuntu LTS, you refer to Ubuntu 14.04 LTS, right? Why don't you just install the package that ships in that Ubuntu release? http://packages.ubuntu.com/trusty/libapache2-mod-proxy-msrpc

APR_CFLAGS needs to be set to the string that would be printed when you run 'pkg-config --cflags apr-1', and APR_LIBS needs to be set to the string that would be printed when you run 'pkg-config --libs apr-1'.

You can help pkg-config to find your local APR installation by setting the environment variable PKG_CONFIG_PATH.

As this is not an issue with mod_proxy_msrpc, I am closing this issue now. Please consult the pkg-config manual or the web for further help on how to use pkg-config with packages installed in local installation paths.
