### ISSUE TITLE
Help with 401 Unauthorized: why is it requiring authentication?

### ISSUE THREAD

**Issue by romanogit** [bombadil/mod_proxy_msrpc#20]
Can you help me with the 401 error bellow?

[Sat May 17 20:30:28.853973 2014] [proxy_msrpc:debug] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(524): [client 189.106.176.110:61533] RPC_IN_DATA: client auth: NTLM
[Sat May 17 20:30:28.890692 2014] [proxy_msrpc:trace1] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(1374): [client 189.106.176.110:61533] RPC_IN_DATA: HTTP request sent to 00.00.00.00:443 (xxx.xxx.xxx.com), now waiting for a response
[Sat May 17 20:30:28.913368 2014] [proxy_msrpc:trace1] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(928): [client 189.106.176.110:61533] RPC_IN_DATA: server auth offer: NTLM
[Sat May 17 20:30:28.913533 2014] [proxy_msrpc:trace1] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(928): [client 189.106.176.110:61533] RPC_IN_DATA: server auth offer: Negotiate
[Sat May 17 20:30:28.913674 2014] [proxy_msrpc:trace1] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(928): [client 189.106.176.110:61533] RPC_IN_DATA: server auth offer: Basic
[Sat May 17 20:30:28.913810 2014] [proxy_msrpc:debug] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(1045): [client 189.106.176.110:61533] RPC_IN_DATA: server auth: NTLM, Negotiate, Basic
[Sat May 17 20:30:28.913943 2014] [proxy_msrpc:debug] [pid 17863:tid 140450052695808] mod_proxy_msrpc.c(1063): [client 189.106.176.110:61533] RPC_IN_DATA: server refused MSRPC request for /rpc/rpcproxy.dll?xxx.xxx.xxx.com:6002: [HTTP/1.1 401 Unauthorized]

**Comment by bombadil** [comment]
There is something going wrong with NTLM authentication. The server 
doesn't like the NTLM message forwarded by mod_proxy_msrpc from the 
client to the server.

I have seen this behavior already in other setups. Apparently on its way 
through your reverse proxy (mod_proxy_msrpc) there is something 
happening to NTLM requests that the server doesn't like. As I have no 
clue yet, I would consider NTLM support in mod_proxy_msrpc broken for 
the moment.

Could you please try with other authentication methods configured in the 
client (i.e. Outlook)?

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
