### ISSUE TITLE
./configure failed due missing lib "Check"

### ISSUE THREAD

**Issue by hpschulz** [bombadil/mod_proxy_msrpc#23]
Hi There,

i'm trying to install these Module on CentOs 6.5. By "./configure" i got the error:

configure: error: Package requirements (check >= 0.9.4) were not met:

No package 'check' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

But i've installed  0.9.8-1.1.el6 and the librarys are in /usr/lib64.

What can i Do?

Thanks for help.

Peter

**Comment by bombadil** [comment]
Hi Peter,

I am sorry, but I don't know CentOs so I don't know what is required to build mod_proxy_msrpc on that distro. According to the pkg-config manpage the PKG_CONFIG_PATH can be set to directories that should be searched for .pc files. In your case the file check.pc couldn't be found. Please check the pkg-config documentation for further help.

Best regards,
Micha Lenk

**Comment by samverstraete** [comment]
Hi,

I had the same problem. I did install check, however, i forgot to install check-devel, so
yum install check-devel
did the trick for me.

Sam
