### ISSUE TITLE
Support "oldies" kernel

### ISSUE THREAD

**Issue by fonya** [bombadil/mod_proxy_msrpc#24]
Hi,

I like to use msrpc proxy for centos 5, I recompile everything, which is needed, /apache, php, apr, etc/, but I can't recompile kernel itself, I must use "official", but this kernel doesn't support inotify_init1 function, and O_CLOEXEC, IN_CLOEXEC. I try to make it itself, but I'm not a programmer, sorry :(
I try something this:
# ifndef O_CLOEXEC
# define O_CLOEXEC       0        /\* set close_on_exec, not supported before kernel 2.6.23 */
# endif
# if HAVE_INOTIFY_INIT1

```
        int inotify_fd = inotify_init1(IN_CLOEXEC);
```
# else

```
        int inotify_fd = inotify_init (); 
```
# endif

And it's needed to modify the configure.ac too (added inotify_init1 function check):

# Checks for library functions.
AC_FUNC_MEMCMP
AC_CHECK_FUNCS([strcasecmp strchr strrchr inotify_init1])

I copy this from qemu code.

Thank You!

Fonya

**Comment by bombadil** [comment]
Hi,

the inotify approach is an ugly cludge that eventually should get replaced by something better for synchronizing independent processes sharing only a common identifier. I just didn't get around to make that happen yet. Any suggestions helping to get rid of inotify are more than welcome.

**Comment by bombadil** [comment]
I've just committed the suggested changes. Please check whether that fixes the issue for you.

**Comment by fonya** [comment]
Hello,

Thank you, I'll try about tomorrow!

On h, 2014-08-18 at 05:17 -0700, Micha Lenk wrote:

> I've just committed the suggested changes. Please check whether that
> fixes the issue for you.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Szabo Akos fonya@fatav.hu
Mobil: +36209707781
Skype: fonya_HU
GTalk: fonya1
