### ISSUE TITLE
Bad response from server (503 RPC error)

### ISSUE THREAD

**Issue by umbertoz** [bombadil/mod_proxy_msrpc#25]
Hi,

I'm not able to access to Exchange because an issue with RPC_OUT_DATA.

[Mon Sep 01 17:45:12.805234 2014] [proxy_msrpc:debug] [pid 24758] mod_proxy_msrpc.c(524): [client 89.96.242.178:41728] RPC_OUT_DATA: client auth: Basic
[Mon Sep 01 17:45:12.817438 2014] [proxy_msrpc:debug] [pid 24763] mod_proxy_msrpc.c(1447): [client 89.96.242.178:41727] RPC_IN_DATA: request headers successfully sent to server (null) (webmail.xxx.xxx.xxx)
[Mon Sep 01 17:45:12.817529 2014] [proxy_msrpc:debug] [pid 24763] mod_proxy_msrpc.c(1468): [client 89.96.242.178:41727] RPC_IN_DATA: initial PDU successfully sent to server (null) (webmail.xxx.xxx.xxx)
[Mon Sep 01 17:45:12.821375 2014] [proxy_msrpc:debug] [pid 24758] mod_proxy_msrpc.c(1447): [client 89.96.242.178:41728] RPC_OUT_DATA: request headers successfully sent to server (null) (webmail.xxx.xxx.xxx)
[Mon Sep 01 17:45:12.821439 2014] [proxy_msrpc:debug] [pid 24758] mod_proxy_msrpc.c(1468): [client 89.96.242.178:41728] RPC_OUT_DATA: initial PDU successfully sent to server (null) (webmail.xxx.xxx.xxx)
[Mon Sep 01 17:45:12.824376 2014] [proxy_msrpc:error] [pid 24758] [client 89.96.242.178:41728] RPC_OUT_DATA: bad response from server: [HTTP/1.0 503 RPC Error: 6ba]

Any idea?

Thank you.

**Comment by umbertoz** [comment]
Hi,

I made a mistake. Now it's working.

**Comment by bombadil** [comment]
Hi,

For the help of other users that might run into the same issue, would you mind to describe what the mistake was and what you did to make your setup working?

Thanks for the feedback anyways...

Regards,
Micha

**Comment by umbertoz** [comment]
Hi,

the mistake was a misconfigured httpd.conf and /etc/hosts.

On /etc/hosts and httpd.conf (ProxyPass line) you must insert the DNS local name of Exchange Server (eg.: NAMESERVER.LOCAL) and not the real DNS name.

**Comment by bombadil** [comment]
Ok, thanks for the hint. Hopefully it helps others to get their configuration right.
I am closing this issue now.
