### ISSUE TITLE
How to run mod_proxy_msrpc with SELinux being enabled?

### ISSUE THREAD

**Issue by gulikoza** [bombadil/mod_proxy_msrpc#28]
Hi,

Thanks for the amazing work! I was successfully able to setup mod_proxy_msrpc on Centos6 and Exchange 2013.

One issue that I encountered was SELinux blocking mod_proxy_msrpc. As setting a secure proxy server is one of the key points of using apache reverseproxy in front of Exchange, there should some guidelines for setting Selinux.

If anybody else has this problem, I was able to debug it. The Outlook session will fail as follows:

[Sun Oct 12 08:00:19.354439 2014] [proxy_msrpc:error] [pid 13016](9)Bad file descriptor: [client xx.xx.xx.xx:58006] RPC_IN_DATA: Failed to sync Outlook Session 381b0776-52a2-648f-3a61-b0081ac21173: -1
[Sun Oct 12 08:00:19.354584 2014] [proxy_msrpc:error] [pid 13016] [client xx.xx.xx.xx:58006] RPC_IN_DATA: The registered Outlook Session 381b0776-52a2-648f-3a61-b0081ac21173 is in unexpected state 'BROKEN'
[Sun Oct 12 08:00:24.318429 2014] [proxy_msrpc:error] [pid 13018](9)Bad file descriptor: [client xx.xx.xx.xx:58008] RPC_IN_DATA: Failed to sync Outlook Session 8cf34bdc-5735-d466-9b52-0c0fdad1a27f: -1
[Sun Oct 12 08:00:24.318583 2014] [proxy_msrpc:error] [pid 13018] [client xx.xx.xx.xx:58008] RPC_IN_DATA: The registered Outlook Session 8cf34bdc-5735-d466-9b52-0c0fdad1a27f is in unexpected state 'TUNNEL'

audit.log shows:

type=AVC msg=audit(1413097376.604:95): avc:  denied  { read } for  pid=1974 comm="httpd" path="inotify" dev=inotifyfs ino=1 scontext=unconfined_u:system_r:httpd_t:s0 tcontext=system_u:object_r:inotifyfs_t:s0 tclass=dir

```
    Was caused by:
            Missing type enforcement (TE) allow rule.

            You can use audit2allow to generate a loadable module to allow this access.
```

The module apparently fails in msrpc_sync_wait() when setting inotify.
Using setenforce 0 allows Outlook session to continue. I'll try to write some SELinux rules, if anybody has any suggestion, please share them as well...

**Comment by gulikoza** [comment]
I've written a module and added it to my selinux policy. This seems to work for me:

module mod_proxy_msrpc 1.0;

require {
    type httpd_t;
    class file { open { getattr read ioctl lock } };
    class dir { getattr search open read lock ioctl };
}

fs_list_inotifyfs(httpd_t);

**Comment by bombadil** [comment]
I hope to eventually be able to drop this inotify hack entirely. But for the time being, I guess your notes are quite helpful for those running mod_proxy_msrpc together with SELinux. So, thank you very much for sharing them here.

**Comment by avoidik** [comment]
Sorry for bumping old thread, but my selinux module builder complains on 'fs_list_inotifyfs' line. What's wrong?
PS. audit2allow helped with this solution

```
module mod_proxy_msrpc 1.0;

require {
        type httpd_t;
        type inotifyfs_t;
        class dir read;
}

#============= httpd_t ==============
allow httpd_t inotifyfs_t:dir read;
```

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't answer this question anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
