### ISSUE TITLE
X-Forwarded-For header would be helpful

### ISSUE THREAD

**Issue by hkelley** [bombadil/mod_proxy_msrpc#29]
The module forwards all original request headers but it does not include the X-Forwarded-For information.  

https://github.com/bombadil/mod_proxy_msrpc/blob/master/src/mod_proxy_msrpc.c#L1436 

 /\* Step Four: Send HTTP request headers to the backend server */
status = proxy_msrpc_send_request_headers(r, locurl, rdata->server_bb,
backend, backend->connection);

That would be very useful information to receive on the back end for security logging purposes (the Sophos UTM sends it for requests that do not run through this module).

**Comment by bombadil** [comment]
Thanks for the enhancement suggestion.

As I have no time to work on this right now, let me just add some comments. A prospective
implementation should mimic the behavior of mod_proxy_http as described here:
http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers
It should also obey the ProxyVia settings as described here
http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxyvia

**Comment by bombadil** [comment]
Patch/pull request welcome.

**Comment by hkelley** [comment]
I'd be inclined to try the changes myself but, even if they worked, I'd be eliminating any possibility of Sophos UTM support for the appliance.

**Comment by bombadil** [comment]
That's only true if you try to fix it yourself on the UTM.

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
