### ISSUE TITLE
2 Warnings during make

### ISSUE THREAD

**Issue by FerronN** [bombadil/mod_proxy_msrpc#30]
Running the config file I've got the Configure: error: some of the required header files could not be found. It says uuid.h usability no, uuid.h presence no, uuid.h no. I'm running centos 7. Could somebody tell me what i'm missing?

**Comment by FerronN** [comment]
Fixed it I had to install libuuid-devel-2.23.2-26.el7.x86_64 , libuuid-devel was not enough

**Comment by FerronN** [comment]
Sorry guys, the problem above was solveable for me, but this one...

[root@localhost mod_proxy_msrpc]# make
make -C src all
make[1]: Entering directory `/usr/src/mod_proxy_msrpc/src'
apxs -luuid  -c mod_proxy_msrpc.c msrpc_pdu_parser.c msrpc_sync.c
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                     c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                     ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                      -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                        -I/usr/include/apr-1   -c -o mod_proxy_msrpc.lo mod_proxy_msrpc.c && touch mod_                     proxy_msrpc.slo
mod_proxy_msrpc.c: In function 'proxy_msrpc_handler':
mod_proxy_msrpc.c:1412:17: warning: format '%llu' expects argument of type 'long                      long unsigned int', but argument 8 has type 'apr_off_t' [-Wformat=]
                 ap_log_rerror(APLOG_MARK, APLOG_ERR, 0, r,
                 ^
mod_proxy_msrpc.c:1412:17: warning: format '%lld' expects argument of type 'long                      long int', but argument 9 has type 'apr_int64_t' [-Wformat=]
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                     c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                     ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                      -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                        -I/usr/include/apr-1   -c -o msrpc_pdu_parser.lo msrpc_pdu_parser.c && touch ms                     rpc_pdu_parser.slo
/usr/lib64/apr-1/build/libtool --silent --mode=compile gcc -std=gnu99 -prefer-pi                     c -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-stro                     ng --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -DLINUX                      -D_REENTRANT -D_GNU_SOURCE -pthread -I/usr/include/httpd  -I/usr/include/apr-1                        -I/usr/include/apr-1   -c -o msrpc_sync.lo msrpc_sync.c && touch msrpc_sync.slo
/usr/lib64/apr-1/build/libtool --silent --mode=link gcc -std=gnu99 -Wl,-z,relro,                     -z,now   -o mod_proxy_msrpc.la  -luuid -rpath /usr/lib64/httpd/modules -module -                     avoid-version    msrpc_sync.lo msrpc_pdu_parser.lo mod_proxy_msrpc.lo
make[1]: Leaving directory`/usr/src/mod_proxy_msrpc/src'

**Comment by bombadil** [comment]
This is just a compiler warning, so the binaries should get built 
anyways.

Or do you get other (real) errors?

**Comment by FerronN** [comment]
Thanks for the quick response. The webserver will start when I add the module and add the OutlookAnywherePassthrough On. But the OutlookAnywhere still won't work. I've tested it with the connectivity tool and I get 2 different rpc error.

The remote server returned an error: (401) Unauthorized.
Type: Microsoft.Exchange.Tools.ExRca.Extensions.MapiTransportException
Stapeltracering:
at Microsoft.Exchange.Tools.ExRca.Extensions.MapiRpcTestClient.PingProtocolProxy(String endpointIdentifier)
at Microsoft.Exchange.Tools.ExRca.Tests.MapiPingProxyTest.PerformTestReally()
Details uitzondering:
Bericht: The remote server returned an error: (401) Unauthorized.
Type: System.Net.WebException
Stapeltracering:
at System.Net.HttpWebRequest.GetResponse()
at RpcPingLib.RpcPing.PingProxy(String internalServerFqdn, String endpoint)
at Microsoft.Exchange.Tools.ExRca.Extensions.MapiRpcTestClient.PingProtocolProxy(String endpointIdentifier)
Verstreken tijd: 160 ms."

And a other one but I can't generate it at the moment

**Comment by FerronN** [comment]
When I put the Exchange server to the internet without the apache within everything works fine, so I know it's not a problem with my exchange setup

**Comment by bombadil** [comment]
Please follow the instructions in the DIAGNOSTICS section of the README.
What debug log messages do you get in your setup?

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
