### ISSUE TITLE
authentication problem 

### ISSUE THREAD

**Issue by mwichern** [bombadil/mod_proxy_msrpc#32]
Hello,

i've configured apache 2.4 as reverse proxy for my exchange 2010 installation. OWA, OAB, Active-Sync works fine. Now i've setup OutlookAnywhere with the proxy_msrpc plugin. but i can't connect with outlook. i tried basic and ntlm authentication, but no success.

following the reverse proxy configuration:
# Outlook Anywhere
# the hostname is added in /etc/hosts

OutlookAnywherePassthrough On
LogLevel info proxy_msrpc:trace2
ProxyPass /rpc http://exchange.internalrpc
ProxyPassReverse /rpc http://exchange.internal/rpc

the outlook anywhere config:

PSComputerName                  : exchange.internal
RunspaceId                      : d7dc368c-1f7b-40fe-beb8-983cd7c0a893
ServerName                      : exchange
SSLOffloading                   : False
ExternalHostname                : mail.externalURL.de
ClientAuthenticationMethod      : Basic
IISAuthenticationMethods        : {Basic}
XropUrl                         :
MetabasePath                    : IIS://exchange.internal/W3SVC/1/ROOT/Rpc
Path                            : C:\Windows\System32\RpcProxy
ExtendedProtectionTokenChecking : None
ExtendedProtectionFlags         : {}
ExtendedProtectionSPNList       : {}
Server                          : exchange
AdminDisplayName                :
ExchangeVersion                 : 0.10 (14.0.100.0)
Name                            : Rpc (Default Web Site)

Identity                        : exchange\Rpc (Default Web Site)
Guid                            : 84e2a8f4-fbde-4585-a91a-13d1d317e781
ObjectCategory                  : behrens-dom.local/Configuration/Schema/ms-Exch-Rpc-Http-Virtual-Directory
ObjectClass                     : {top, msExchVirtualDirectory, msExchRpcHttpVirtualDirectory}
WhenChanged                     : 02.02.2016 11:09:20
WhenCreated                     : 26.11.2015 09:22:14
WhenChangedUTC                  : 02.02.2016 10:09:20
WhenCreatedUTC                  : 26.11.2015 08:22:14
OrganizationId                  :
OriginatingServer               : dc01.internal
IsValid                         : True

the apache error log trying to connect to exchange:

[Tue Feb 02 11:08:24.853956 2016] [ssl:info] [pid 13687:tid 3023027008] [client XXX.XXX.193.78:60065] AH01964: Connection to child 196 established (server mail.externalURL.de:443)
[Tue Feb 02 11:08:24.925074 2016] [proxy_msrpc:debug] [pid 13687:tid 3023027008] mod_proxy_msrpc.c(1276): [client XXX.XXX.193.78:60065] declining due to bad method: POST
[Tue Feb 02 11:08:28.258144 2016] [proxy_msrpc:trace1] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1347): [client XXX.XXX.193.78:60065] RPC_IN_DATA: serving URL http://exchange.internal/rpc/rpcproxy.dll?exchange.internal:6001
[Tue Feb 02 11:08:28.258191 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1157): [client XXX.XXX.193.78:60065] RPC_IN_DATA: acquired backend connection 0xa92db058
[Tue Feb 02 11:08:28.284715 2016] [ssl:info] [pid 13624:tid 2897136448] [client XXX.XXX.193.78:60076] AH01964: Connection to child 83 established (server mail.externalURL.de:443)
[Tue Feb 02 11:08:28.355894 2016] [proxy_msrpc:trace1] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1347): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: serving URL http://exchange.internal/rpc/rpcproxy.dll?exchange.internal:6001
[Tue Feb 02 11:08:28.356101 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1157): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: acquired backend connection 0xb64c2058
[Tue Feb 02 11:08:28.357434 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(776): [client XXX.XXX.193.78:60065] RPC_IN_DATA: got 10 bytes of request body from client
[Tue Feb 02 11:08:28.357457 2016] [proxy_msrpc:trace1] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(838): [client XXX.XXX.193.78:60065] RPC_IN_DATA: MSRPC PDU length: 104 (10 already in buffer)
[Tue Feb 02 11:08:28.357464 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(844): [client XXX.XXX.193.78:60065] RPC_IN_DATA: trying to get 94 more bytes from request body
[Tue Feb 02 11:08:28.357473 2016] [proxy_msrpc:trace1] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(880): [client XXX.XXX.193.78:60065] RPC_IN_DATA: MSRPC PDU length: 104 (completely in buffer)
[Tue Feb 02 11:08:28.357488 2016] [proxy_msrpc:debug] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(911): [client XXX.XXX.193.78:60065] RPC_IN_DATA: got initial MSRPC pdu (104 bytes) for Outlook Session (null)
[Tue Feb 02 11:08:28.357494 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(146): [client XXX.XXX.193.78:60065] RPC_IN_DATA: trying to register outlook session 7e33f270-34e2-d962-127e-3e8c963a3414 in state 'INIT'
[Tue Feb 02 11:08:28.357549 2016] [proxy_msrpc:debug] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(186): [client XXX.XXX.193.78:60065] RPC_IN_DATA: Successfully registered outlook session 7e33f270-34e2-d962-127e-3e8c963a3414 in state 'INIT'
[Tue Feb 02 11:08:28.357571 2016] [proxy_msrpc:debug] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(524): [client XXX.XXX.193.78:60065] RPC_IN_DATA: client auth: Basic
[Tue Feb 02 11:08:28.357613 2016] [proxy_msrpc:debug] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1447): [client XXX.XXX.193.78:60065] RPC_IN_DATA: request headers successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.357681 2016] [proxy_msrpc:debug] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1468): [client XXX.XXX.193.78:60065] RPC_IN_DATA: initial PDU successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.359218 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(776): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: got 10 bytes of request body from client
[Tue Feb 02 11:08:28.359332 2016] [proxy_msrpc:trace1] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(838): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: MSRPC PDU length: 76 (10 already in buffer)
[Tue Feb 02 11:08:28.359427 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(844): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: trying to get 66 more bytes from request body
[Tue Feb 02 11:08:28.359566 2016] [proxy_msrpc:trace1] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(880): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: MSRPC PDU length: 76 (completely in buffer)
[Tue Feb 02 11:08:28.359808 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(911): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: got initial MSRPC pdu (76 bytes) for Outlook Session (null)
[Tue Feb 02 11:08:28.359916 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(524): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: client auth: Basic
[Tue Feb 02 11:08:28.360103 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1447): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: request headers successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.360354 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1468): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: initial PDU successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.360559 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1045): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: server auth: missing
[Tue Feb 02 11:08:28.360748 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1063): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: server refused MSRPC request for /rpc/rpcproxy.dll?exchange.internal:6001: [HTTP/1.1 403 Forbidden]
[Tue Feb 02 11:08:28.361035 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1076): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: Forwarded all HTTP response headers to client
[Tue Feb 02 11:08:28.361153 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1086): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: HTTP response body size: 74 bytes
[Tue Feb 02 11:08:28.361325 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1113): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: Forwarded the HTTP response to client
[Tue Feb 02 11:08:28.361423 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1482): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: proxy_msrpc_read_server_response() returned status code 403
[Tue Feb 02 11:08:28.361556 2016] [proxy_msrpc:error] [pid 13624:tid 2897136448] [client XXX.XXX.193.78:60076] RPC_OUT_DATA: server 10.1.0.131:80 (exchange.internal) did not accept initial PDU (HTTP status code 403)
[Tue Feb 02 11:08:28.361655 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(212): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: trying to update Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 to state 'BROKEN'
[Tue Feb 02 11:08:28.361791 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(231): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 found in cache
[Tue Feb 02 11:08:28.361928 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(241): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 updated to state BROKEN'
[Tue Feb 02 11:08:28.362278 2016] [proxy_msrpc:error] [pid 13687:tid 2972670784] [client XXX.XXX.193.78:60065] RPC_IN_DATA: Failed to sync Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414: 2
[Tue Feb 02 11:08:28.362309 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(212): [client XXX.XXX.193.78:60065] RPC_IN_DATA: trying to update Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 to state 'BROKEN'
[Tue Feb 02 11:08:28.362321 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(231): [client XXX.XXX.193.78:60065] RPC_IN_DATA: Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 found in cache
[Tue Feb 02 11:08:28.362327 2016] [proxy_msrpc:error] [pid 13687:tid 2972670784] [client XXX.XXX.193.78:60065] RPC_IN_DATA: The registered Outlook Session 7e33f270-34e2-d962-127e-3e8c963a3414 is in unexpected state 'BROKEN'
[Tue Feb 02 11:08:28.362333 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1563): [client XXX.XXX.193.78:60065] RPC_IN_DATA: handler working on backend connection 0xa92db058 finished, returning connection to pool
[Tue Feb 02 11:08:28.362378 2016] [proxy_msrpc:trace2] [pid 13687:tid 2972670784] mod_proxy_msrpc.c(1568): [client XXX.XXX.193.78:60065] RPC_IN_DATA: setting keepalive from 0 to AP_CONN_CLOSE
[Tue Feb 02 11:08:28.362658 2016] [proxy_msrpc:trace2] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1563): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: handler working on backend connection 0xb64c2058 finished, returning connection to pool

i think this is the error why i could not logged in:

[Tue Feb 02 11:08:28.360103 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1447): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: request headers successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.360354 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1468): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: initial PDU successfully sent to server 10.1.0.131:80 (exchange.internal)
[Tue Feb 02 11:08:28.360559 2016] [proxy_msrpc:debug] [pid 13624:tid 2897136448] mod_proxy_msrpc.c(1045): [client XXX.XXX.193.78:60076] RPC_OUT_DATA: server auth: missing

but when i try to the autodiscover configuration, that works fine.

any ideas?

**Comment by FerronN** [comment]
I had the same, everything work except outlook anywhere. I use a IIS server as reverse proxy now.

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
