### ISSUE TITLE
centos 7 x64 apache 2.4.6

### ISSUE THREAD

**Issue by ghost** [bombadil/mod_proxy_msrpc#34]
i have multiple error messages in apache error log after enabling module
[:error] [pid 26116] AH00000: sd_notifyf returned an error -111

**Comment by bombadil** [comment]
This doesn't really look like it is related to mod_proxy_msrpc. Is disabling mod_proxy_msrpc really fixing these error log messages?

**Comment by makadizsolt** [comment]
Just for your information: I successfully compiled and used this module on an up-to-date CentOS 7 (7.8.2003) with x64 Apache version 2.4.6-93

**Comment by bombadil** [comment]
> Just for your information: I successfully compiled and used this module on an up-to-date CentOS 7 (7.8.2003) with x64 Apache version 2.4.6-93

Thanks for this piece of information. Unfortunately it doesn't help in debugging the runtime issue.

**Comment by bombadil** [comment]
This Apache module for Outlook Anywhere support in reverse proxy setups is
obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is
deprecated by MAPI over HTTP, which seems to work just fine using the regular
reverse proxy settings in Apache (i.e. mod_proxy_http).

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
