### ISSUE TITLE
RDG 2019

### ISSUE THREAD

**Issue by wensont** [bombadil/mod_proxy_msrpc#35]
Hello I receive this error during connect to RDG 2019 (also cannot open any of remoteapp from rdg)
[Mon Apr 22 17:54:47.738366 2019] [ssl:info] [pid 16607] [remote rdg_ip:443] AH01964: Connection to child 0 established (server rdg_fqdn:443)
[Mon Apr 22 17:54:47.767449 2019] [proxy_msrpc:debug] [pid 16605] mod_proxy_msrpc.c(1276): [client 127.0.0.1:58494] declining due to bad method: GET, referer: https://domain/RDWeb/Pages/en-US/Default.aspx

**Comment by bombadil** [comment]
I am sorry, but RDG 2019 is currently not supported by this module.

**Comment by boyfromgermany** [comment]
after some trying i managed to get RDGW 2019 working 

i used `apt install libapache2-mod-proxy-msrpc`
(is that the even the same module ?) 

Here is my config

```
<VirtualHost *:80>
    ServerName rdgw.example.com
    RewriteEngine on
    RewriteCond %{SERVER_NAME} =rdgw.example.com
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerName rdgw.example.com
    SSLEngine On
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    SSLCertificateFile /etc/letsencrypt/live/rdgw.example.com/cert.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/rdgw.example.com/privkey.pem
    SSLCertificateChainFile /etc/letsencrypt/live/rdgw.example.com/fullchain.pem

#    ProxyPass /  http://10.10.10.110/
#    ProxyPassReverse / http://10.10.10.110/

    ProxyPreserveHost On
    ProxyAddHeaders On
    RequestHeader set X-Forwarded-Proto "https"

    OutlookAnywherePassthrough on
        ProxyPass /rpc https://10.10.10.110/rpc
        ProxyPassReverse /rpc https://10.10.10.110/rpc
        ProxyPass /Rpc https://10.10.10.110/Rpc
        ProxyPassReverse /Rpc https://10.10.10.110/Rpc


</VirtualHost>

```

**Comment by bombadil** [comment]
Thank you for your feedback.
Yes, it's the same module.
