### ISSUE TITLE
some of the required header files could not be found

### ISSUE THREAD

**Issue by RealGrimbi** [bombadil/mod_proxy_msrpc#36]
I am getting the following error when running ./configure:
configure: error: some of the required header files could not be found.

OS: latest CentOS 8

I installed the following via yum:
yum groupinstall "Development Tools"
yum install httpd-devel
yum install check-devel
yum install header-devel
yum install libstdc++-devel
yum install gcc-toolset-9-libstdc++-devel
yum install kernel-headers
headers_module ist active

Anyone knows which package is missing?

**Comment by RealGrimbi** [comment]
yum install libuuid-devel
solved it for me

**Comment by bombadil** [comment]
Thanks for documenting how you solved it. I'll close the issue now.
