### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bisontim** [bombadil/mod_proxy_msrpc#4]
Hallo.
It could be useful to have mod_proxy_msrpc on windows environment.

**Comment by bombadil** [comment]
I am sorry, but currently I don't have enough resources to develop Apache httpd on Windows.

Patches are welcome though...

**Comment by bombadil** [comment]
I'm sorry, but I have to admit I won't fix this issue anymore.

This project is obsolete for the following reason. Since Exchange 2016 the MSRPC protocol is deprecated by MAPI over HTTP, which seems to work just fine using the regular reverse proxy settings in Apache (i.e. mod_proxy_http).
