### ISSUE TITLE
undefined symbol: ap_global_mutex_create at apache2 restart

### ISSUE THREAD

**Issue by alemke** [bombadil/mod_proxy_msrpc#9]
We successfully compiled the module, copied .libs/mod_proxy_msrpc.so to /usr/lib/apache2/modules/mod_proxy_msrpc.so
We created the file /etc/apache2/modules-available/proxy_msrpc.load with content
LoadModule proxy_msrpc_module /usr/lib/apache2/modules/mod_proxy_msrpc.so
a2enmod proxy_msprc, 
service apache2 restart
ERROR:
undefined symbol: ap_global_mutex_create
Apache2 is running but not working. 
What's wrong?
And, do we really need to use a Proxy Server? Why not publish the server to the internet?
Thank you!
A. Lemke

**Comment by bombadil** [comment]
Regarding the error displayed when restarting Apache, your build system used to build mod_proxy_msrpc very likely doesn't match the build system Apache httpd was built with. I.e. mod_proxy_msrpc.so expects the symbol ap_global_mutex_create to be present in httpd, but for what ever reason it isn't available. What version of Apache httpd are you trying to use?

Regarding the question of whether you really need to use a proxy server or not: This is a question that depends highly on your local requirements, so I can't answer this in general. The module mod_proxy_msrpc is intended to be used in cases where you do _not_ want to expose IIS/Exchange directly to the internet.

**Comment by alemke** [comment]
Hi!
Thanks for your fast answer. We are using Debian Wheezy (7.0) and have installed Apache2 via apt-get. 
According to http://packages.debian.org/wheezy/apache2 it is Version 2.2.22-13.
apxs is not in this package of apache2. Firstly, we installed packages apache2-prefork-dev, apache2-threaded-dev as they contain apxs2. 
Then we got a compile error that ap_socache.h could not be found. 
So we looked for this header and found it in package apache2-dev which is unfortunately not available in Debian 7, but in 8(Jessie). As this package also contains apxs and apxs2 we removed the packages apache2-prefork-dev and apache2-threaded-dev, added the Jessie source to /etc/apt/sources.list and installted apache2-dev.
Then we were able to compile proxy_msrpc, but got the error restarting apache2.

**Comment by bombadil** [comment]
In Debian Jessie Apache httpd switched from version 2.2.x to 2.4.x. But the modules compiled for Apache httpd 2.4.x do not work for Apache 2.2.x (this is a general problem with Apache modules that is not specific to mod_proxy_msrpc). So your only option here is to install and run the module using Apache httpd 2.4.x.

Anyhow, your issue basically boils down to the same issue as mentioned in issue #5 (compiling fails with Apache 2.2.x). So I am going to closing this issue as a duplicate now.
